-- V4: Evolución del simulador a los requerimientos de Sprint 1
-- 1. Actualización de Roles
ALTER TABLE usuarios MODIFY COLUMN rol ENUM('ADMINISTRADOR', 'ANALISTA', 'DOCENTE') NOT NULL DEFAULT 'ANALISTA';

-- 2. Evolución de la tabla alternativas para soportar ramificación A/B/C
ALTER TABLE alternativas ADD COLUMN grupo VARCHAR(10) DEFAULT NULL;

-- 3. Actualización de la Fase 1
UPDATE fases 
SET nom_fase = '1ra FASE: El escenario de crisis',
    desc_fase = 'Yachay-Tech ha detectado que, aunque hay mucho tráfico en su web, las ventas de su tablet "Kallpa" se detienen en el carrito de compras. En este momento usted debe decidir cuál será la ruta de acción para identificar los stoppers que no permiten concluir la compra del producto.'
WHERE numero_fase = 1;

-- 4. Limpieza de alternativas previas de la Fase 1 (para evitar conflictos de ID o lógica antigua)
DELETE FROM puntajes WHERE alternativa_id IN (SELECT id_alternativa FROM alternativas WHERE fase_id = (SELECT id_fase FROM fases WHERE numero_fase = 1));
DELETE FROM alternativas WHERE fase_id = (SELECT id_fase FROM fases WHERE numero_fase = 1);

-- 5. Inserción de los nuevos Análisis y sus Instrumentos (Fase 1)
-- Grupo A: Análisis de Estímulos
INSERT INTO alternativas (fase_id, grupo, desc_alternativa, puntaje, retroalimentacion, orden) VALUES
((SELECT id_fase FROM fases WHERE numero_fase = 1), 'A', 'Auditoría de Contenido Multimedia y UX', 5, 
'¡Excelente elección! Estás aplicando el concepto de sensaciones al entorno digital. Revisar cómo el cliente percibe visualmente la tablet es fundamental para un negocio que opera con un cliente digitalizado.\n\n[RESULTADOS]\n- Falla sensorial: Las fotos en la web son estáticas y no muestran la fluidez del procesador en multitarea, lo que impide que el cliente genere una sensación de velocidad.\n- Contenido "escondido": El contenido educativo de "Yachay-Hub" está en una pestaña secundaria, lo que dificulta que el estudiante perceiba de inmediato cómo la tablet le ayudará a mejorar sus notas.\n\n[CONCLUSION]\nHas identificado que el entorno digital no está estimulando los sentidos del cliente.', 1);

INSERT INTO alternativas (fase_id, grupo, desc_alternativa, puntaje, retroalimentacion, orden) VALUES
((SELECT id_fase FROM fases WHERE numero_fase = 1), 'A', 'Test de Producto en Puntos de Venta (Pop-up Stores)', 10, 
'¡Muy bien pensado! Al permitir el contacto físico, estás activando el canal sensorial completo del cliente. Esto es vital para romper la creencia de que la tecnología local es de ''baja calidad'', permitiendo que la percepción se base en la experiencia real y no en prejuicios; sin embargo, los datos que recojas pueden estar sesgados por parte de quien aplique el test.\n\n[RESULTADOS]\n- Calidad de Materiales: El 85% de los padres se sorprendió positivamente al tocar el aluminio reforzado, ya que esperaban plástico barato debido al precio bajo.\n- Limitación Técnica: Algunos usuarios reportaron que el brillo de la pantalla en exteriores (plazas principales) es insuficiente, lo que afecta la sensación de utilidad en el campo.\n- Comportamiento Social: Se observó que los padres solo se acercan al módulo si ven a otros padres probando el equipo primero.\n\n[CONCLUSION]\nHas descubierto que el contacto físico rompe la creencia negativa de ''mala calidad''.', 2);

INSERT INTO alternativas (fase_id, grupo, desc_alternativa, puntaje, retroalimentacion, orden) VALUES
((SELECT id_fase FROM fases WHERE numero_fase = 1), 'A', 'Prueba de Rendimiento Crítico de Yachay-Hub', 20, 
'¡Decisión estratégica superior! Has seleccionado una herramienta que analiza profundamente la motivación del cliente. Al demostrar el valor de ''Yachay-Hub'' sin conexión y la durabilidad de la batería en condiciones reales, estás atacando directamente la necesidad psicológica de seguridad que el padre de familia peruano exige para aprobar la compra.\n\n[RESULTADOS]\n- Resistencia física: Al ver la tablet caer desde 1 metro sin sufrir daños, el nivel de estrés de los padres bajó drásticamente y su intención de compra subió un 60%.\n- Valor educativo: El uso de "Yachay-Hub" sin internet generó una sensación de "alivio" y "empoderamiento" en estudiantes de zonas rurales, quienes lo ven como su única oportunidad de competir con alumnos de Lima.\n- Factor seguridad: Se descubrió que el miedo al "robo" (falta de seguridad física en la calle) pesa más que el miedo a que el equipo se malogre.\n\n[CONCLUSION]\nHas llegado a la raíz, la motivación de seguridad no es solo técnica, es también contextual (el entorno peruano). Ahora sabes que, para vender, debes ofrecer tranquilidad total.', 3);

-- Grupo B: Análisis de la Toma de Decisiones
INSERT INTO alternativas (fase_id, grupo, desc_alternativa, puntaje, retroalimentacion, orden) VALUES
((SELECT id_fase FROM fases WHERE numero_fase = 1), 'B', 'Encuesta de Referidos y canales de información', 5, 
'¡Buen trabajo! Has elegido una herramienta eficiente para mapear las influencias externas cuantitativamente. Identificar si el cliente llega por una red social o por recomendación de un amigo es el primer paso para entender el entorno del consumidor.\n\n[RESULTADOS]\n- Impacto de Redes vs. Confianza: El 65% de los clientes llegó por un video de TikTok, pero el 80% solo compró tras consultar a un "amigo que sabe de tecnología".\n- Barrera del Precio: El 40% de los padres mencionó que "el precio le hacía dudar" hasta que alguien de su confianza le dio el visto bueno.\n- Falta de Validación: Se ha identificado la falta de una figura de autoridad técnica local que valide la marca masivamente.\n\n[CONCLUSION]\nLa información es útil para detectar tendencias. Te da el qué (la recomendación es clave), pero no el cómo.', 1);

INSERT INTO alternativas (fase_id, grupo, desc_alternativa, puntaje, retroalimentacion, orden) VALUES
((SELECT id_fase FROM fases WHERE numero_fase = 1), 'B', 'Etnografía Digital en Comunidades Universitarias', 10, 
'¡Excelente enfoque! Al observar el comportamiento en su entorno natural, estás analizando los factores sociales y los grupos de referencia de la Generación Z. Este instrumento te permite ver la influencia de los pares en tiempo real, algo crucial para productos tecnológicos.\n\n[RESULTADOS]\n- Percepción de Marca: En los grupos de WhatsApp de estudiantes, se descubrió que Yachay-Tech es vista como "la tablet para estudiar", pero se recomienda una marca global para "lucirse en la facultad".\n- Líderes de Opinión: Existe un líder de opinión (el delegado o el alumno más aplicado) que tiene el poder de validar o destruir la reputación de la tablet con un solo comentario.\n- Factor Estatus: El factor social del estatus y la presión de grupo asocia "lo peruano" con algo funcional pero no aspiracional.\n\n[CONCLUSION]\nAl observar sin intervenir, has captado la ''jerga'' y el sentimiento real de la Generación Z. Posees datos cualitativos potentes sobre el factor social.', 2);

INSERT INTO alternativas (fase_id, grupo, desc_alternativa, puntaje, retroalimentacion, orden) VALUES
((SELECT id_fase FROM fases WHERE numero_fase = 1), 'B', 'Shadowing y Entrevista en el "Punto de Decisión" (Tienda Física)', 20, 
'¡Decisión estratégica sobresaliente! Has seleccionado el instrumento más profundo para este camino. Al observar la dinámica real entre el decisor y el influyente (padre-hijo), puedes identificar exactamente en qué etapa de la toma de decisiones surge el conflicto.\n\n[RESULTADOS]\n- Dinámica Padre-Hijo: Se observó que el hijo convence al padre en el pasillo usando argumentos de "tareas y software", pero al momento de sacar la tarjeta, el padre se detiene, mira las marcas globales vecinas y le pregunta al vendedor: "¿Cuál me recomienda usted?".\n- El Rol del Vendedor: Si el vendedor duda o no conoce Yachay-Tech, el padre aborta la compra inmediatamente por falta de seguridad.\n- El Quiebre: El vendedor actúa como influyente crítico y la inseguridad del padre aparece en la etapa final del proceso.\n\n[CONCLUSION]\nLa información es de altísima calidad y estratégica. Has presenciado el momento exacto del quiebre (la ''hora de la verdad''). Tienes evidencia directa de cómo interactúan las influencias internas (deseo del hijo) con las externas (vendedor y entorno).', 3);

-- Grupo C: Análisis de Actitudes y Creencias
INSERT INTO alternativas (fase_id, grupo, desc_alternativa, puntaje, retroalimentacion, orden) VALUES
((SELECT id_fase FROM fases WHERE numero_fase = 1), 'C', 'Encuesta Digital Estándar (Post-Abandono)', 5, 
'¡Buena idea! Has elegido una herramienta que te permite obtener datos cuantitativos rápidamente y a bajo costo. Es un paso valioso para identificar tendencias generales en el comportamiento del cliente digitalizado.\n\n[RESULTADOS]\n- Desconfianza técnica: El 55% de los encuestados marcó la opción "Desconfianza en la durabilidad del hardware".\n- Paradoja del precio: El 80% considera que el precio de S/ 850.00 es "muy bueno", pero el 40% teme que lo barato signifique mala calidad.\n- Desconocimiento de valor: El 70% de los usuarios digitales no sabía que la tablet incluye contenido del MINEDU que funciona sin internet.\n\n[CONCLUSION]\nHas obtenido datos fríos. Sabes qué está pasando (miedo a la durabilidad), pero no sabes el porqué.', 1);

INSERT INTO alternativas (fase_id, grupo, desc_alternativa, puntaje, retroalimentacion, orden) VALUES
((SELECT id_fase FROM fases WHERE numero_fase = 1), 'C', 'Entrevistas a Profundidad con el "Comprador Dual"', 10, 
'¡Excelente enfoque! Al incluir a ambos actores, estás reconociendo las influencias en la toma de decisiones. Estás logrando captar matices emocionales y motivaciones de seguridad que una encuesta ignoraría.\n\n[RESULTADOS]\n- El Hijo (Gen Z): Tiene una actitud positiva hacia el software "Yachay-Hub", pero siente que la tablet no tiene "onda" o estatus frente a sus compañeros.\n- El Padre (Gen X): Es el principal stopper. Su creencia está basada en experiencias pasadas negativas con marcas ensambladas en Perú. Solo compraría si hubiera una garantía física cerca de su casa.\n- Conflicto de intereses: La etapa de "Evaluación de alternativas" se bloquea porque el padre prioriza la motivación de seguridad (durabilidad) mientras el hijo busca autorrealización (estudio).\n\n[CONCLUSION]\nHas identificado un choque generacional de necesidades que detiene la compra.', 2);

INSERT INTO alternativas (fase_id, grupo, desc_alternativa, puntaje, retroalimentacion, orden) VALUES
((SELECT id_fase FROM fases WHERE numero_fase = 1), 'C', 'Focus Group de "Asociación Implícita y Proyectiva"', 20, 
'¡Impresionante decisión estratégica! Has seleccionado la herramienta cualitativa más potente para este escenario. Este instrumento te permitirá ''hackear'' las creencias arraigadas del consumidor peruano y entender el componente cognitivo real de su actitud negativa.\n\n[RESULTADOS]\n- Metáfora de Usuario: Los participantes describieron a Yachay-Tech como "un estudiante esforzado pero que usa ropa genérica", mientras que a la competencia global la ven como "el estudiante exitoso que todos admiran".\n- Prueba Ciega: En una prueba "ciega" (sin marcas), el 90% prefirió la fluidez de la pantalla de la tablet Kallpa. Sin embargo, al ponerle el logo de Yachay-Tech, la percepción de calidad bajó automáticamente.\n- Prejuicio Cognitivo: El cliente peruano asocia la tecnología nacional con "lo básico", ignorando que las especificaciones son de alta gama.\n\n[CONCLUSION]\nEl problema no es el producto, es el prejuicio. Has descubierto que la marca sufre de una "actitud de rechazo por origen".', 3);
